{{- $srvHostFull := include "cap.deploymentHostFull" (merge (dict "name" "srv" "deployment" .Values.srv) . ) }}
{{- $defaultAppUrls := dict
  "getDependencies" (printf "https://%s%s" $srvHostFull .Values.saas_registry.getDependencies)
  "onSubscription" (printf "https://%s%s" $srvHostFull .Values.saas_registry.onSubscription)
  "onSubscriptionAsync" false
  "onUnSubscriptionAsync" false
  "callbackTimeoutMillis" 300000
}}
{{- $defaultParameters := dict
    "xsappname" .Values.xsuaa.parameters.xsappname
    "appName" .Values.xsuaa.parameters.xsappname
    "displayName" .Chart.Name
    "description" .Chart.Description
    "category" "CAP Application"
    "appUrls" $defaultAppUrls
}}
{{- include "cap.service-instance" (merge (dict "defaultParameters" $defaultParameters ) .) }}
